
import { LinkItem, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'ia', name: 'AI', icon: 'wand-magic-sparkles' },
  { id: 'jogo', name: 'GAMES', icon: 'gamepad' },
  { id: 'streaming', name: 'TV', icon: 'tv' },
  { id: 'social', name: 'SOCIAL', icon: 'share-nodes' },
  { id: 'compra', name: 'SHOP', icon: 'cart-shopping' },
  { id: 'leitura', name: 'LEITURA', icon: 'book-open' },
  { id: 'explorar', name: 'EXPLORAR', icon: 'compass' },
];

export const INITIAL_LINKS: LinkItem[] = [
  // --- CATEGORIA 1: IA ---
  { id: 'ia-gamma', name: 'Gamma', url: 'https://gamma.app', description: 'Criação de apresentações e documentos com IA.', category: 'ia', subCategory: 'IA', baseViews: 3421, compatibility: 'dual' },
  { id: 'ia-ideogram', name: 'Ideogram', url: 'https://ideogram.ai', description: 'Geração de imagens com foco em tipografia.', category: 'ia', subCategory: 'IA', baseViews: 1245, compatibility: 'dual' },
  { id: 'ia-suno', name: 'Suno AI', url: 'https://suno.ai', description: 'Criação de músicas completas com IA.', category: 'ia', subCategory: 'IA', baseViews: 890, compatibility: 'dual' },
  { id: 'ia-manus', name: 'Manus', url: 'https://manus.ai', description: 'Assistente de escrita e produtividade.', category: 'ia', subCategory: 'IA', baseViews: 560, compatibility: 'dual' },
  { id: 'ia-leonardo', name: 'Leonardo AI', url: 'https://leonardo.ai', description: 'Geração de imagens e assets de alta qualidade.', category: 'ia', subCategory: 'IA', baseViews: 2134, compatibility: 'dual' },
  { id: 'ia-chatgpt', name: 'ChatGPT', url: 'https://chat.openai.com', description: 'Modelo de linguagem líder para conversação.', category: 'ia', subCategory: 'IA', baseViews: 5671, compatibility: 'dual' },
  { id: 'ia-luzia', name: 'LuzIA', url: 'https://www.luzia.com', description: 'IA para WhatsApp e Telegram.', category: 'ia', subCategory: 'IA', baseViews: 3210, compatibility: 'dual' },
  { id: 'ia-monica', name: 'Monica', url: 'https://monica.im', description: 'Copiloto de IA para produtividade.', category: 'ia', subCategory: 'IA', baseViews: 920, compatibility: 'dual' },
  { id: 'ia-lovable', name: 'Lovable', url: 'https://lovable.so', description: 'Criação de sites e apps com IA.', category: 'ia', subCategory: 'IA', baseViews: 450, compatibility: 'dual' },
  { id: 'ia-roboneo', name: 'RoboNeo', url: 'https://roboneo.ai', description: 'Automação inteligente.', category: 'ia', subCategory: 'IA', baseViews: 310, compatibility: 'dual' },
  { id: 'ia-ebookmaker', name: 'Ebookmaker', url: 'https://ebookmaker.ai', description: 'Criação automática de eBooks.', category: 'ia', subCategory: 'IA', baseViews: 280, compatibility: 'dual' },
  { id: 'ia-deepseek', name: 'DeepSeek', url: 'https://www.deepseek.com', description: 'Modelo de linguagem de alto desempenho.', category: 'ia', subCategory: 'IA', baseViews: 1540, compatibility: 'dual' },
  { id: 'ia-notebooklm', name: 'NotebookLM', url: 'https://notebooklm.google', description: 'IA de pesquisa e análise do Google.', category: 'ia', subCategory: 'IA', baseViews: 780, compatibility: 'dual' },
  { id: 'ia-imagineart', name: 'ImagineArt', url: 'https://www.imagine.art', description: 'Criação artística com IA.', category: 'ia', subCategory: 'IA', baseViews: 640, compatibility: 'dual' },
  { id: 'ia-nanobanana', name: 'Nano Banana', url: 'https://nanobananas.ai', description: 'Exploração de modelos leves de IA.', category: 'ia', subCategory: 'IA', baseViews: 520, compatibility: 'dual' },
  { id: 'ia-veo3', name: 'Veo 3', url: 'https://deepmind.google/technologies/veo', description: 'Geração de vídeo de alta fidelidade do Google.', category: 'ia', subCategory: 'IA', baseViews: 890, compatibility: 'dual' },
  { id: 'ia-flux', name: 'Flux', url: 'https://flux.ai', description: 'Design de hardware e esquemas com IA.', category: 'ia', subCategory: 'IA', baseViews: 410, compatibility: 'dual' },
  { id: 'ia-deepseekchat', name: 'DeepSeek Chat', url: 'https://chat.deepseek.com', description: 'Interface de chat do DeepSeek.', category: 'ia', subCategory: 'IA', baseViews: 1100, compatibility: 'dual' },
  { id: 'ia-vidguru', name: 'Vidguru', url: 'https://www.vidguru.ai', description: 'Edição de vídeo inteligente.', category: 'ia', subCategory: 'IA', baseViews: 340, compatibility: 'dual' },
  { id: 'ia-transkriptor', name: 'Transkriptor', url: 'https://transkriptor.com', description: 'Transcrição de áudio em texto.', category: 'ia', subCategory: 'IA', baseViews: 670, compatibility: 'dual' },
  { id: 'ia-scholarai', name: 'ScholarAI', url: 'https://www.scholarai.io', description: 'IA para pesquisadores acadêmicos.', category: 'ia', subCategory: 'IA', baseViews: 560, compatibility: 'dual' },
  { id: 'ia-researchrabbit', name: 'Research Rabbit', url: 'https://www.researchrabbit.ai', description: 'Mapeamento de literatura acadêmica.', category: 'ia', subCategory: 'IA', baseViews: 490, compatibility: 'dual' },
  { id: 'ia-grammarly', name: 'Grammarly', url: 'https://www.grammarly.com', description: 'Assistente de escrita e gramática.', category: 'ia', subCategory: 'IA', baseViews: 3400, compatibility: 'dual' },
  { id: 'ia-notionai', name: 'Notion AI', url: 'https://www.notion.so/product/ai', description: 'Escrita e organization dentro do Notion.', category: 'ia', subCategory: 'IA', baseViews: 2100, compatibility: 'dual' },
  { id: 'ia-trelloai', name: 'Trello IA', url: 'https://trello.com', description: 'Automação de quadros no Trello.', category: 'ia', subCategory: 'IA', baseViews: 890, compatibility: 'dual' },
  { id: 'ia-consensus', name: 'Consensus', url: 'https://consensus.app', description: 'Motor de busca baseado em ciência.', category: 'ia', subCategory: 'IA', baseViews: 450, compatibility: 'dual' },
  { id: 'ia-canva', name: 'Canva', url: 'https://www.canva.com', description: 'Design facilitado com ferramentas de IA.', category: 'ia', subCategory: 'IA', baseViews: 4800, compatibility: 'dual' },
  { id: 'ia-synthesia', name: 'Synthesia', url: 'https://www.synthesia.io', description: 'Geração de vídeos com avatares de IA.', category: 'ia', subCategory: 'IA', baseViews: 730, compatibility: 'dual' },
  { id: 'ia-elevenlabs', name: 'ElevenLabs', url: 'https://elevenlabs.io', description: 'A melhor voz de IA do mundo.', category: 'ia', subCategory: 'IA', baseViews: 2900, compatibility: 'dual' },
  { id: 'ia-typecast', name: 'Typecast', url: 'https://typecast.ai', description: 'Dublagem e vozes realistas.', category: 'ia', subCategory: 'IA', baseViews: 320, compatibility: 'dual' },
  { id: 'ia-mendeley', name: 'Mendeley', url: 'https://www.mendeley.com', description: 'Gerenciador de referências.', category: 'ia', subCategory: 'IA', baseViews: 800, compatibility: 'dual' },
  { id: 'ia-replitai', name: 'Replit AI', url: 'https://replit.com', description: 'Codificação assistida por IA.', category: 'ia', subCategory: 'IA', baseViews: 1200, compatibility: 'dual' },
  { id: 'ia-copilot', name: 'GitHub Copilot', url: 'https://github.com/features/copilot', description: 'O par programador de IA.', category: 'ia', subCategory: 'IA', baseViews: 3100, compatibility: 'dual' },
  { id: 'ia-dungeon', name: 'AI Dungeon', url: 'https://play.aidungeon.com', description: 'RPG de aventura infinita.', category: 'ia', subCategory: 'IA', baseViews: 670, compatibility: 'dual' },
  { id: 'ia-wonder', name: 'Wonder', url: 'https://www.artbreeder.com', description: 'Criação de personagens e arte.', category: 'ia', subCategory: 'IA', baseViews: 540, compatibility: 'dual' },
  { id: 'ia-sudowrite', name: 'Sudowrite', url: 'https://www.sudowrite.com', description: 'IA para escritores de ficção.', category: 'ia', subCategory: 'IA', baseViews: 430, compatibility: 'dual' },
  { id: 'ia-faceapp', name: 'FaceApp', url: 'https://www.faceapp.com', description: 'Edição de rosto foto-realista.', category: 'ia', subCategory: 'IA', baseViews: 1200, compatibility: 'dual' },
  { id: 'ia-toongineer', name: 'Toongineer', url: 'https://toongineer.com', description: 'Transforme fotos em desenhos animados.', category: 'ia', subCategory: 'IA', baseViews: 310, compatibility: 'dual' },
  { id: 'ia-meme', name: 'AI Meme Generator', url: 'https://imgflip.com/ai-meme', description: 'Crie memes instantâneos com IA.', category: 'ia', subCategory: 'IA', baseViews: 890, compatibility: 'dual' },
  { id: 'ia-quillbot', name: 'QuillBot', url: 'https://quillbot.com', description: 'Parafraseador e resumidor.', category: 'ia', subCategory: 'IA', baseViews: 2300, compatibility: 'dual' },
  { id: 'ia-n8n', name: 'N8N', url: 'https://n8n.io', description: 'Automação de fluxo de trabalho.', category: 'ia', subCategory: 'IA', baseViews: 450, compatibility: 'dual' },
  { id: 'ia-base44', name: 'Base 44', url: 'https://base44.com', description: 'Ferramentas de IA avançadas.', category: 'ia', subCategory: 'IA', baseViews: 210, compatibility: 'dual' },
  { id: 'ia-heyboss', name: 'Hey Boss AI', url: 'https://heyboss.ai', description: 'Assistente corporativo.', category: 'ia', subCategory: 'IA', baseViews: 180, compatibility: 'dual' },
  { id: 'ia-aistudio', name: 'Google AI Studio', url: 'https://aistudio.google.com', description: 'Desenvolvimento rápido com Gemini.', category: 'ia', subCategory: 'IA', baseViews: 3400, compatibility: 'dual' },
  { id: 'ia-mgx', name: 'MGX', url: 'https://tinyurl.com/mtajx5zb', description: 'Plataforma de IA experimental.', category: 'ia', subCategory: 'IA', baseViews: 290, compatibility: 'dual' },
  { id: 'ia-maestro', name: 'Maestro IA', url: 'https://maestrohub.site/', description: 'Hub de projetos e letras para Suno.', category: 'ia', subCategory: 'IA', baseViews: 1489, compatibility: 'dual' },
  { id: 'ia-nemo', name: 'Nemo Video', url: 'https://www.nemovideo.com', description: 'Geração de vídeos rápida.', category: 'ia', subCategory: 'IA', baseViews: 240, compatibility: 'dual' },
  { id: 'ia-readdy', name: 'Readdy AI', url: 'https://readdy.ai', description: 'Preparação para produtividade.', category: 'ia', subCategory: 'IA', baseViews: 310, compatibility: 'dual' },
  { id: 'ia-10web', name: '10Web', url: 'https://10web.io', description: 'Plataforma que cria sites completos e hospedagem automaticamente usando inteligência artificial.', category: 'ia', subCategory: 'IA WEB', baseViews: 1200, compatibility: 'dual' },
  { id: 'ia-righthair', name: 'RightHair AI', url: 'https://righthair.ai', description: 'Visualizador que aplica diferentes cortes e cores de cabelo em sua foto usando IA.', category: 'ia', subCategory: 'ESTILO', baseViews: 850, compatibility: 'dual' },
  { id: 'ia-lmarena', name: 'LMArena', url: 'https://lmarena.ai', description: 'Comparador de modelos de IA onde você testa e vota nas melhores respostas entre robôs.', category: 'ia', subCategory: 'LABS', baseViews: 3400, compatibility: 'dual' },
  { id: 'ia-humanornot', name: 'Human or Not?', url: 'https://humanornot.so', description: 'Jogo de chat social para adivinhar se o interlocutor é um humano ou uma inteligência artificial.', category: 'ia', subCategory: 'GAME/IA', baseViews: 7600, compatibility: 'dual' },
  { id: 'ot-gemini', name: 'GEM', url: 'https://gemini.google.com/gem/1rg79HwPux2K5LaFqF97oMeQdhbLsrd43?usp=sharing', description: 'IA avançada do Google para tudo.', category: 'ia', subCategory: 'IA GOOGLE', baseViews: 9432, compatibility: 'dual' },
  { id: 'ia-blackbox', name: 'Blackbox AI', url: 'https://www.blackbox.ai', description: 'Inteligência Artificial para Código e Chat.', category: 'ia', subCategory: 'IA CÓDIGO', baseViews: 4500, compatibility: 'dual' },

  // --- CATEGORIA 2: JOGO ---
  { id: 'j-gam-onl', name: 'Gam.onl', url: 'https://www.gam.onl', description: 'Plataforma de mini-jogos viciantes.', category: 'jogo', subCategory: 'WEB GAMES', baseViews: 4500, compatibility: 'dual' },
  { id: 'j-gartic', name: 'Gartic.io', url: 'https://gartic.io', description: 'O clássico jogo de desenhar e adivinhar online.', category: 'jogo', subCategory: 'SOCIAL', baseViews: 12000, compatibility: 'dual' },
  { id: 'j-arcade-arch', name: 'Internet Archive: Arcade', url: 'https://archive.org/details/internetarcade', description: 'Milhares de clássicos dos fliperamas emulados no navegador.', category: 'jogo', subCategory: 'RETRO', baseViews: 5600, compatibility: 'pc' },
  { id: 'j-nealfun', name: 'Neal.fun', url: 'https://neal.fun', description: 'Coleção de experiências web curiosas e joguinhos zen.', category: 'jogo', subCategory: 'EXPERIÊNCIA', baseViews: 9800, compatibility: 'dual' },
  { id: 'j-jigsaw', name: 'Jigsaw Planet', url: 'https://www.jigsawplanet.com', description: 'Quebra-cabeças online com milhares de opções grátis.', category: 'jogo', subCategory: 'PUZZLE', baseViews: 3200, compatibility: 'dual' },
  { id: 'j-mess-abeto', name: 'Messenger (Abeto)', url: 'https://messenger.abeto.co', description: 'Comunicação e jogos sociais leves.', category: 'jogo', subCategory: 'SOCIAL', baseViews: 1500, compatibility: 'dual' },
  { id: 'j-deepnight', name: 'Deepnight', url: 'https://deepnight.net', description: 'Jogos indies de alta qualidade técnica e visual.', category: 'jogo', subCategory: 'INDIE', baseViews: 2100, compatibility: 'dual' },
  { id: 'j-krunker-main', name: 'Krunker', url: 'https://krunker.io', description: 'FPS tático rápido com visual voxel.', category: 'jogo', subCategory: 'FPS', baseViews: 25000, compatibility: 'dual' },
  { id: 'j-play-classic', name: 'Play Classic Games', url: 'https://playclassic.games', description: 'Portal dedicado a clássicos do console e PC.', category: 'jogo', subCategory: 'RETRO', baseViews: 4300, compatibility: 'dual' },
  { id: 'j-retro-cz', name: 'Retro Games', url: 'https://retro.games.cz', description: 'Acervo europeu de jogos antigos emulados.', category: 'jogo', subCategory: 'RETRO', baseViews: 1900, compatibility: 'dual' },
  { id: 'j-classic-reload', name: 'Classic Reload', url: 'https://classicreload.com', description: 'Preservação de jogos abandonware para jogar via web.', category: 'jogo', subCategory: 'RETRO', baseViews: 3800, compatibility: 'dual' },
  { id: 'j-hordes', name: 'Hordes.io', url: 'https://hordes.io', description: 'MMORPG 3D simples e funcional direto no browser.', category: 'jogo', subCategory: 'MMO', baseViews: 7600, compatibility: 'dual' },
  { id: 'j-dos-games', name: 'Play DOS Games', url: 'https://playdosgames.com', description: 'Reviva a era de ouro do MS-DOS.', category: 'jogo', subCategory: 'RETRO', baseViews: 2900, compatibility: 'pc' },
  { id: 'j-pako', name: 'Pako Highway', url: 'https://pakohighway.online', description: 'Corrida frenética de perseguição policial.', category: 'jogo', subCategory: 'CORRIDA', baseViews: 6700, compatibility: 'dual' },
  { id: 'j-bloxd-j', name: 'Bloxd.io', url: 'https://bloxd.io', description: 'Mundo sandbox estilo Minecraft com vários modos.', category: 'jogo', subCategory: 'SANDBOX', baseViews: 18000, compatibility: 'dual' },
  { id: 'j-drifted', name: 'Drifted', url: 'https://drifted.com', description: 'O melhor simulador de drift via navegador.', category: 'jogo', subCategory: 'CORRIDA', baseViews: 5400, compatibility: 'dual' },
  { id: 'j-lost-gamer', name: 'Lost Gamer', url: 'https://lostgamer.io', description: 'Geoguessr de mundos de vídeo games.', category: 'jogo', subCategory: 'TRIVIA', baseViews: 3100, compatibility: 'dual' },
  { id: 'j-eagler', name: 'Eaglercraft', url: 'https://eaglercraft.com', description: 'Minecraft Java Edition rodando no navegador.', category: 'jogo', subCategory: 'SANDBOX', baseViews: 22000, compatibility: 'pc' },
  { id: 'j-geofs', name: 'Geo-FS', url: 'https://geo-fs.com', description: 'Simulador de voo global usando mapas reais.', category: 'jogo', subCategory: 'SIMULADOR', baseViews: 4500, compatibility: 'pc' },
  { id: 'j-worldguessr', name: 'WorldGuessr', url: 'https://worldguessr.com', description: 'Alternativa gratuita ao Geoguessr.', category: 'jogo', subCategory: 'GEOGRAFIA', baseViews: 8900, compatibility: 'dual' },
  { id: 'j-itch-j', name: 'Itch.io', url: 'https://itch.io', description: 'A maior loja de jogos independentes do mundo.', category: 'jogo', subCategory: 'PORTAL', baseViews: 45000, compatibility: 'dual' },
  { id: 'j-playcs', name: 'Play-CS', url: 'https://play-cs.com', description: 'Counter-Strike 1.6 direto no seu navegador.', category: 'jogo', subCategory: 'FPS', baseViews: 31000, compatibility: 'pc' },
  { id: 'j-wormax', name: 'Wormax.io', url: 'https://wormax.io', description: 'Jogo competitivo de minhocas com poderes.', category: 'jogo', subCategory: 'IO GAME', baseViews: 14000, compatibility: 'dual' },
  { id: 'j-diep', name: 'Diep.io', url: 'https://diep.io', description: 'Arena de tanques com sistema de evolução.', category: 'jogo', subCategory: 'IO GAME', baseViews: 21000, compatibility: 'dual' },
  { id: 'j-splix', name: 'Splix.io', url: 'https://splix.io', description: 'Conquiste território neste jogo de estratégia rápido.', category: 'jogo', subCategory: 'IO GAME', baseViews: 9200, compatibility: 'dual' },
  { id: 'j-retrocc', name: 'RetroGames.cc', url: 'https://retrogames.cc', description: 'Emulador online para consoles clássicos.', category: 'jogo', subCategory: 'RETRO', baseViews: 7300, compatibility: 'pc' },
  { id: 'j-akinator', name: 'Akinator', url: 'https://pt.akinator.com', description: 'O gênio que adivinha em quem você está pensando.', category: 'jogo', subCategory: 'TRIVIA', baseViews: 6700, compatibility: 'dual' },
  { id: 'j-1v1-lol', name: '1v1.LOL', url: 'https://1v1.lol', description: 'Simulador de construção e tiro estilo Fortnite.', category: 'jogo', subCategory: 'TIRO', baseViews: 28000, compatibility: 'dual' },
  { id: 'j-pacman', name: 'World\'s Biggest Pac-Man', url: 'https://worldsbiggestpacman.com', description: 'Mapa infinito de Pac-Man criado por usuários.', category: 'jogo', subCategory: 'ARCADE', baseViews: 4100, compatibility: 'dual' },
  { id: 'j-haxball', name: 'HaxBall', url: 'https://haxball.com', description: 'Futebol físico 2D em tempo real.', category: 'jogo', subCategory: 'ESPORTE', baseViews: 12000, compatibility: 'pc' },
  { id: 'j-slowroads', name: 'Slow Roads', url: 'https://slowroads.io', description: 'Simulador de direção processual infinita.', category: 'jogo', subCategory: 'DRIVING', baseViews: 5600, compatibility: 'pc' },
  { id: 'j-mess-eu', name: 'Mess', url: 'https://mess.eu.org', description: 'Ferramentas e emuladores experimentais.', category: 'jogo', subCategory: 'LABS', baseViews: 1200, compatibility: 'pc' },
  { id: 'j-emupedia', name: 'Emupedia', url: 'https://emupedia.net', description: 'Preservação de sistemas operacionais e jogos web antigos.', category: 'jogo', subCategory: 'RETRO', baseViews: 15000, compatibility: 'pc' },

  // --- CATEGORIA 3: STREAMING ---
  { id: 'st-temp', name: 'Temp Mail', url: 'https://temp-mail.org', description: 'E-mails temporários para cadastros.', category: 'streaming', subCategory: 'UTILITÁRIO APOIO', baseViews: 4120, compatibility: 'dual' },
  { id: 'st-globo', name: 'Globoplay', url: 'https://globoplay.globo.com', description: 'A maior plataforma de streaming nacional.', category: 'streaming', subCategory: 'NACIONAL', baseViews: 3450, compatibility: 'dual' },
  { id: 'st-pluto', name: 'Pluto TV', url: 'https://pluto.tv', description: 'Canais de TV grátis e filmes.', category: 'streaming', subCategory: '100% GRÁS', baseViews: 2300, compatibility: 'dual' },
  { id: 'st-vix', name: 'VIX Cine e TV', url: 'https://www.vix.com/pt-br', description: 'Streaming gratuito de filmes e séries.', category: 'streaming', subCategory: '100% GRÁTIS', baseViews: 890, compatibility: 'dual' },
  { id: 'st-netmovies', name: 'NetMovies', url: 'https://www.netmovies.com.br', description: 'Filmes clássicos e novos gratuitos.', category: 'streaming', subCategory: 'FILMES GRÁTIS', baseViews: 1100, compatibility: 'dual' },
  { id: 'st-plus-sbt', name: '+SBT', url: 'https://www.sbt.com.br/mais-sbt', description: 'Todo o conteúdo do SBT online.', category: 'streaming', subCategory: 'TV GRÁTIS', baseViews: 1200, compatibility: 'dual' },
  { id: 'st-band', name: 'BandPlay', url: 'https://www.bandplay.com', description: 'Acesse a programação da Band.', category: 'streaming', subCategory: 'TV GRÁTIS', baseViews: 950, compatibility: 'dual' },
  { id: 'st-spcine', name: 'Spcine Play', url: 'https://www.spcineplay.com.br', description: 'Filmes brasileiros e internacionais.', category: 'streaming', subCategory: 'ACERVO CULTURAL', baseViews: 420, compatibility: 'dual' },
  { id: 'st-itau', name: 'Itaú Cultural Play', url: 'https://www.itauculturalplay.com.br', description: 'Cultura e cinema brasileiro.', category: 'streaming', subCategory: 'ACERVO CULTURAL', baseViews: 380, compatibility: 'dual' },
  { id: 'st-crunchy', name: 'Crunchyroll', url: 'https://www.crunchyroll.com', description: 'A maior biblioteca de animes.', category: 'streaming', subCategory: 'ANIMES', baseViews: 3543, compatibility: 'dual' },
  { id: 'st-plex', name: 'Plex', url: 'https://www.plex.tv/watch-free', description: 'Streaming de filmes e TV gratuito.', category: 'streaming', subCategory: 'FILMES & TV', baseViews: 1500, compatibility: 'dual' },
  { id: 'st-rakuten-tv', name: 'Rakuten TV', url: 'https://rakuten.tv/br', description: 'Cinema em casa.', category: 'streaming', subCategory: 'FILMES ONLINE', baseViews: 670, compatibility: 'dual' },
  { id: 'st-viki', name: 'Rakuten Viki', url: 'https://www.viki.com', description: 'Doramas e produções asiáticas.', category: 'streaming', subCategory: 'DORAMAS', baseViews: 1800, compatibility: 'dual' },
  { id: 'st-yt-movies', name: 'YouTube Filmes', url: 'https://www.youtube.com/feed/storefront', description: 'Filmes para alugar ou gratuitos.', category: 'streaming', subCategory: 'OFICIAL', baseViews: 2100, compatibility: 'dual' },
  { id: 'st-archive', name: 'Internet Archive', url: 'https://archive.org/details/movies', description: 'Domínio público e clássicos.', category: 'streaming', subCategory: 'CLÁSSICOS', baseViews: 3100, compatibility: 'dual' },
  { id: 'st-redbull', name: 'Red Bull TV', url: 'https://www.redbull.com/br-pt', description: 'Esportes de ação e aventura.', category: 'streaming', subCategory: 'ESPORTES', baseViews: 890, compatibility: 'dual' },
  { 
    id: 'st-tvgarden', 
    name: 'TV Garden', 
    url: 'https://tv.garden', 
    description: 'Globo 3D interativo para sintonizar canais de TV locais ao vivo ao redor do mundo.', 
    category: 'streaming', 
    subCategory: 'TV AO VIVO', 
    baseViews: 8900, 
    compatibility: 'pc',
    logoUrl: 'https://img.icons8.com/color/96/earth-planet.png'
  },
  { 
    id: 'st-rave', 
    name: 'Rave', 
    url: 'https://beta.rave.io', 
    description: 'Plataforma para assistir vídeos e filmes em sincronia com amigos à distância.', 
    category: 'streaming', 
    subCategory: 'SOCIAL', 
    baseViews: 5400, 
    compatibility: 'dual',
    logoUrl: 'https://play-lh.googleusercontent.com/al3iXW5FqzF5VjCgHq8KjS7iM5gLqG-xXhXwX9xXhXw=w240-h480-rw'
  },
  { 
    id: 'st-explore', 
    name: 'Explore.org', 
    url: 'https://explore.org', 
    description: 'Transmissões ao vivo de câmeras focadas na natureza e vida selvagem global.', 
    category: 'streaming', 
    subCategory: 'NATUREZA', 
    baseViews: 3200, 
    compatibility: 'dual',
    logoUrl: 'https://img.icons8.com/color/96/bear.png'
  },
  { 
    id: 'st-my90stv', 
    name: 'My 90\'s TV', 
    url: 'https://www.my90stv.com', 
    description: 'Simulador de TV antiga. Troque de canais e assista comerciais e noticiários reais dos anos 90.', 
    category: 'streaming', 
    subCategory: 'NOSTALGIA', 
    baseViews: 4800, 
    compatibility: 'dual',
    logoUrl: 'https://img.icons8.com/color/96/retro-tv.png'
  },
  { 
    id: 'st-archive-anim', 
    name: 'Internet Archive: Animation', 
    url: 'https://archive.org/details/animationandcartoons', 
    description: 'Biblioteca colossal com milhares de desenhos clássicos, Looney Tunes e animações raras.', 
    category: 'streaming', 
    subCategory: 'DESENHOS', 
    baseViews: 12500, 
    compatibility: 'dual',
    logoUrl: 'https://img.icons8.com/color/96/library.png'
  },
  { 
    id: 'st-astronaut', 
    name: 'Astronaut.io', 
    url: 'https://astronaut.io', 
    description: 'Experiência que mostra vídeos do YouTube recém-postados com zero visualizações.', 
    category: 'streaming', 
    subCategory: 'EXPERIÊNCIA', 
    baseViews: 7100, 
    compatibility: 'dual',
    logoUrl: 'https://img.icons8.com/color/96/astronaut.png'
  },
  { id: 'st-famelack', name: 'Famelack TV', url: 'https://famelack.com', description: 'Transmissão e Canais ao Vivo.', category: 'streaming', subCategory: 'TV AO VIVO', baseViews: 3200, compatibility: 'dual' },

  // --- CATEGORIA 4: REDES SOCIAIS ---
  { id: 'soc-yt', name: 'YouTube', url: 'https://www.youtube.com', description: 'Vídeos, música e lives.', category: 'social', subCategory: 'VÍDEOS', baseViews: 9821, compatibility: 'dual' },
  { id: 'soc-reddit', name: 'Reddit', url: 'https://www.reddit.com', description: 'A primeira página da internet.', category: 'social', subCategory: 'COMUNIDADE', baseViews: 2984, compatibility: 'dual' },
  { id: 'soc-discord', name: 'Discord', url: 'https://discord.com', description: 'Lugar de conversa para gamers.', category: 'social', subCategory: 'CONVERSAS', baseViews: 5821, compatibility: 'dual' },
  { id: 'soc-x', name: 'X (Twitter)', url: 'https://x.com', description: 'O que está acontecendo agora.', category: 'social', subCategory: 'NOTÍCIAS', baseViews: 4100, compatibility: 'dual' },
  { id: 'soc-fb', name: 'Facebook', url: 'https://www.facebook.com', description: 'Conecte-se com amigos.', category: 'social', subCategory: 'SOCIAL', baseViews: 3200, compatibility: 'dual' },
  { id: 'soc-ig', name: 'Instagram', url: 'https://www.instagram.com', description: 'Compartilhe seus momentos.', category: 'social', subCategory: 'FOTOS/REELS', baseViews: 6291, compatibility: 'dual' },
  { id: 'soc-tiktok', name: 'TikTok', url: 'https://www.tiktok.com', description: 'Vídeos curtos virais.', category: 'social', subCategory: 'VÍDEOS CURTOS', baseViews: 7672, compatibility: 'dual' },
  { id: 'soc-twitch', name: 'Twitch', url: 'https://www.twitch.tv', description: 'Transmissões ao vivo de jogos.', category: 'social', subCategory: 'LIVES', baseViews: 4500, compatibility: 'dual' },
  { id: 'soc-spotify', name: 'Spotify', url: 'https://www.spotify.com', description: 'Música e podcasts ilimitados.', category: 'social', subCategory: 'MÚSICA', baseViews: 5200, compatibility: 'dual' },
  { id: 'soc-ok', name: 'OK.ru', url: 'https://ok.ru', description: 'Rede social russa popular por seu vasto acervo de filmes e músicas compartilhados por usuários.', category: 'social', subCategory: 'SOCIAL', baseViews: 1200, compatibility: 'dual' },
  { id: 'soc-ometv', name: 'OmeTV', url: 'https://ome.tv', description: 'Plataforma de chat de vídeo aleatório para conversar com desconhecidos (alternativa ao antigo Omegle).', category: 'social', subCategory: 'VIDEO CHAT', baseViews: 3400, compatibility: 'dual' },

  // --- CATEGORIA 5: COMPRAS ---
  { id: 'cp-amazon', name: 'Amazon Brasil', url: 'https://www.amazon.com.br', description: 'Loja global com entrega rápida.', category: 'compra', subCategory: 'GLOBAL', baseViews: 4741, compatibility: 'dual' },
  { id: 'cp-mercado', name: 'Mercado Livre', url: 'https://www.mercadolivre.com.br', description: 'Líder em e-commerce na América Latina.', category: 'compra', subCategory: 'LÍDER BR', baseViews: 5103, compatibility: 'dual' },
  { id: 'cp-shopee', name: 'Shopee Brasil', url: 'https://shopee.com.br', description: 'Ofertass com frete grátis.', category: 'compra', subCategory: 'OFERTAS', baseViews: 6542, compatibility: 'dual' },
  { id: 'cp-aliexpress', name: 'AliExpress', url: 'https://www.aliexpress.com', description: 'Produtos importados direto da China.', category: 'compra', subCategory: 'IMPORTADOS', baseViews: 4200, compatibility: 'dual' },
  { id: 'cp-magalu', name: 'Magazine Luiza', url: 'https://www.magazineluiza.com.br', description: 'Grande varejista brasileiro.', category: 'compra', subCategory: 'VAREJO', baseViews: 3100, compatibility: 'dual' },
  { id: 'cp-americanas', name: 'Americanas', url: 'https://www.americanas.com.br', description: 'Tudo o que você precisa.', category: 'compra', subCategory: 'VAREJO', baseViews: 2800, compatibility: 'dual' },
  { id: 'cp-casasbahia', name: 'Casas Bahia', url: 'https://www.casasbahia.com.br', description: 'Dedicação total a você.', category: 'compra', subCategory: 'VAREJO', baseViews: 1900, compatibility: 'dual' },
  { id: 'cp-extra', name: 'Extra', url: 'https://www.extra.com.br', description: 'Supermercado e eletrônicos.', category: 'compra', subCategory: 'SUPERMERCADO', baseViews: 850, compatibility: 'dual' },
  { id: 'cp-carrefour', name: 'Carrefour', url: 'https://www.carrefour.com.br', description: 'Rede global de supermercados.', category: 'compra', subCategory: 'SUPERMERCADO', baseViews: 920, compatibility: 'dual' },
  { id: 'cp-fastshop', name: 'Fast Shop', url: 'https://www.fastshop.com.br', description: 'Eletrônicos e eletrodomésticos premium.', category: 'compra', subCategory: 'PREMIUM', baseViews: 450, compatibility: 'dual' },
  { id: 'cp-havan', name: 'Havan', url: 'https://www.havan.com.br', description: 'Loja de departamentos completa.', category: 'compra', subCategory: 'DEPARTAMENTOS', baseViews: 1200, compatibility: 'dual' },
  { id: 'cp-kabum', name: 'KaBuM!', url: 'https://www.kabum.com.br', description: 'Tecnologia e Hardware gamer.', category: 'compra', subCategory: 'GAMER/TECH', baseViews: 3400, compatibility: 'dual' },
  { id: 'cp-pichau', name: 'Pichau', url: 'https://www.pichau.com.br', description: 'Hardware e PCs gamer.', category: 'compra', subCategory: 'GAMER/TECH', baseViews: 2100, compatibility: 'dual' },
  { id: 'cp-terabyte', name: 'Terabyte Shop', url: 'https://www.terabyteshop.com.br', description: 'A melhor loja gamer do Brasil.', category: 'compra', subCategory: 'GAMER/TECH', baseViews: 1800, compatibility: 'dual' },
  { id: 'cp-nike', name: 'Nike Brasil', url: 'https://www.nike.com.br', description: 'Artigos esportivos oficiais Nike.', category: 'compra', subCategory: 'ESPORTE', baseViews: 1540, compatibility: 'dual' },
  { id: 'cp-adidas', name: 'Adidas Brasil', url: 'https://www.adidas.com.br', description: 'Artigos esportivos oficiais Adidas.', category: 'compra', subCategory: 'ESPORTE', baseViews: 1200, compatibility: 'dual' },
  { id: 'cp-decathlon', name: 'Decathlon', url: 'https://www.decathlon.com.br', description: 'Tudo para o seu esporte.', category: 'compra', subCategory: 'ESPORTE', baseViews: 890, compatibility: 'dual' },
  { id: 'cp-renner', name: 'Renner', url: 'https://www.lojasrenner.com.br', description: 'Moda feminina, masculina e infantil.', category: 'compra', subCategory: 'MODA', baseViews: 1100, compatibility: 'dual' },
  { id: 'cp-cea', name: 'C&A', url: 'https://www.cea.com.br', description: 'Tendências de moda acessível.', category: 'compra', subCategory: 'MODA', baseViews: 950, compatibility: 'dual' },
  { id: 'cp-riachuelo', name: 'Riachuelo', url: 'https://www.riachuelo.com.br', description: 'Moda e casa.', category: 'compra', subCategory: 'MODA', baseViews: 870, compatibility: 'dual' },
  { id: 'cp-samsung', name: 'Samsung Brasil', url: 'https://www.samsung.com/br', description: 'Smartphones e eletrônicos Samsung.', category: 'compra', subCategory: 'ELETRÔNICOS', baseViews: 2500, compatibility: 'dual' },
  { id: 'cp-apple', name: 'Apple Brasil', url: 'https://www.apple.com/br', description: 'Produtos oficiais Apple no Brasil.', category: 'compra', subCategory: 'PREMIUM', baseViews: 3100, compatibility: 'dual' },
  { id: 'cp-motorola', name: 'Motorola Brasil', url: 'https://www.motorola.com.br', description: 'Smartphones oficiais Motorola.', category: 'compra', subCategory: 'SMARTPHONES', baseViews: 1100, compatibility: 'dual' },
  { id: 'cp-olx', name: 'OLX', url: 'https://www.olx.com.br', description: 'Compre e venda usados perto de você.', category: 'compra', subCategory: 'DESAPEGO', baseViews: 4500, compatibility: 'dual' },
  { id: 'cp-enjoei', name: 'Enjoei', url: 'https://www.enjoei.com.br', description: 'Brechó online e moda usada.', category: 'compra', subCategory: 'MODA USADA', baseViews: 2300, compatibility: 'dual' },

  // --- CATEGORIA 6: EXPLORAR ---
  { id: 'ut-alphacoders', name: 'AlphaCoders 8K', url: 'https://alphacoders.com/popular-8k-wallpapers', description: 'Melhor acervo de wallpapers em 8K.', category: 'explorar', subCategory: 'WALLPAPER 8K', baseViews: 3100, compatibility: 'dual' },
  { id: 'ut-wallhaven', name: 'Wallhaven Top', url: 'https://wallhaven.cc/toplist?page=50', description: 'A elite da arte digital e wallpapers.', category: 'explorar', subCategory: 'ARTE DIGITAL', baseViews: 4500, compatibility: 'dual' },
  { id: 'ut-artstation', name: 'ArtStation Wallpapers', url: 'https://www.artstation.com/search?q=wallpaper', description: 'Wallpapers criados por profissionais.', category: 'explorar', subCategory: 'CONCEPT ART', baseViews: 1800, compatibility: 'dual' },
  { id: 'ut-access', name: 'WallpaperAccess', url: 'https://wallpaperaccess.com', description: 'Coleções temáticas e variadas.', category: 'explorar', subCategory: 'COLEÇÕES', baseViews: 1200, compatibility: 'dual' },
  { id: 'ut-zedge', name: 'Zedge', url: 'https://www.zedge.net/wallpapers', description: 'O maior portal de personalização mobile.', category: 'explorar', subCategory: 'MOBILE FOCUS', baseViews: 6700, compatibility: 'dual' },
  { id: 'ut-pinterest', name: 'Pinterest Wallpapers', url: 'https://www.pinterest.com/search/pins/?q=wallpaper', description: 'Inspiração infinita para sua tela.', category: 'explorar', subCategory: 'INSPIRAÇÃO', baseViews: 9800, compatibility: 'dual' },
  { id: 'ut-wallhere', name: 'WallHere', url: 'https://wallhere.com', description: 'Wallpapers em alta resolução para PC.', category: 'explorar', subCategory: 'ALTA RESOLUÇÃO', baseViews: 920, compatibility: 'dual' },
  { id: 'ut-nexus', name: 'DesktopNexus', url: 'https://www.desktopnexus.com', description: 'Comunidade clássica de wallpapers.', category: 'explorar', subCategory: 'COMUNIDADE', baseViews: 540, compatibility: 'dual' },
  { id: 'ot-cmsp', name: 'Hack CMSP', url: 'https://cmsphacks.xyz/', description: 'Ferramentas utilitárias para CMSP.', category: 'explorar', subCategory: 'ESTUDOS/HACK', baseViews: 3121, compatibility: 'dual' },
  { id: 'ot-subway', name: 'Hack Subway Surf', url: 'https://youtu.be/nvA0fISMfus?si=M0ou9x0-6EszvGB2', description: 'Aprenda a instalar o mod no vídeo.', category: 'explorar', subCategory: 'GAME MOD/VÍDEO', baseViews: 12437, compatibility: 'dual' },
  { id: 'exp-drive', name: 'Drive & Listen', url: 'https://drivenlisten.com', description: 'Dirija virtualmente por cidades do mundo ouvindo rádios locais reais.', category: 'explorar', subCategory: 'EXPERIÊNCIA', baseViews: 8500, compatibility: 'dual' },
  { id: 'exp-mac', name: 'Infinite Mac', url: 'https://infinitemac.org', description: 'Rode versões clássicas do System 7 e Mac OS diretamente no seu navegador.', category: 'explorar', subCategory: 'NOSTALGIA', baseViews: 4200, compatibility: 'pc' },
  { id: 'exp-window', name: 'Window Swap', url: 'https://www.window-swap.com', description: 'Olhe pela janela de alguém em qualquer lugar do mundo.', category: 'explorar', subCategory: 'EXPERIÊNCIA', baseViews: 6700, compatibility: 'dual' },
  { id: 'exp-city', name: 'Citywalki', url: 'https://citywalki.com', description: 'Caminhe virtualmente por cidades famosas com som ambiente imersivo.', category: 'explorar', subCategory: 'TOUR VIRTUAL', baseViews: 3100, compatibility: 'dual' },
  { id: 'exp-azgaar', name: 'Azgaar\'s Fantasy Map Generator', url: 'https://azgaar.github.io', description: 'Gerador avançado de mapas de fantasia para RPG e escrita.', category: 'explorar', subCategory: 'MAPS', baseViews: 9200, compatibility: 'dual' },
  { id: 'exp-donjon', name: 'Donjon', url: 'https://donjon.bin.sh', description: 'Caixa de ferramentas completa para mestres de RPG (Dungeons, Nomes, Itens).', category: 'explorar', subCategory: 'RPG TOOLS', baseViews: 5400, compatibility: 'dual' },
  { id: 'exp-hero', name: 'Hero Forge', url: 'https://heroforge.com', description: 'Criação e design de miniaturas 3D customizadas.', category: 'explorar', subCategory: '3D DESIGN', baseViews: 12000, compatibility: 'dual' },
  { id: 'exp-watabou-city', name: 'Watabou City Generator', url: 'https://watabou.github.io', description: 'Gerador procedimental de mapas de cidades medievais.', category: 'explorar', subCategory: 'MAPS', baseViews: 7300, compatibility: 'dual' },
  { id: 'exp-tabletop', name: 'Tabletop Audio', url: 'https://tabletopaudio.com', description: 'Ambientes sonoros e músicas de 10 minutos para RPG e foco.', category: 'explorar', subCategory: 'ÁUDIO', baseViews: 4100, compatibility: 'dual' },
  { id: 'exp-scrawl', name: 'Dungeon Scrawl', url: 'https://dungeonscrawl.com', description: 'Ferramenta rápida e estilizada para desenhar mapas de masmorras.', category: 'explorar', subCategory: 'MAPS', baseViews: 3800, compatibility: 'pc' },
  { id: 'exp-chartopia', name: 'Chartopia', url: 'https://chartopia.d12dev.com', description: 'Repositório gigante de tabelas aleatórias para RPG.', category: 'explorar', subCategory: 'RPG TOOLS', baseViews: 2900, compatibility: 'dual' },
  { id: 'exp-reroll', name: 'Reroll', url: 'https://reroll.co', description: 'Criação de personagens em Pixel Art para RPG.', category: 'explorar', subCategory: 'PIXEL ART', baseViews: 5600, compatibility: 'dual' },
  { id: 'exp-watabou-itch', name: 'Watabou (Itch.io)', url: 'https://watabou.itch.io', description: 'Coleção de ferramentas procedimentais de design e jogos.', category: 'explorar', subCategory: 'DESIGN', baseViews: 4300, compatibility: 'dual' },
  { id: 'exp-vacation', name: 'Virtual Vacation', url: 'https://virtualvacation.us', description: 'Viaje pelo mundo através de câmeras ao vivo e tours 360.', category: 'explorar', subCategory: 'TOUR VIRTUAL', baseViews: 8100, compatibility: 'dual' },
  { id: 'exp-tiny', name: 'TinyPNG', url: 'https://tinypng.com', description: 'Compressão inteligente de imagens sem perda de qualidade.', category: 'explorar', subCategory: 'TOOLS', baseViews: 15000, compatibility: 'dual' },
  { id: 'exp-floor', name: 'Floor796', url: 'https://floor796.com', description: 'Um imenso projeto colaborativo de animação em uma estação espacial.', category: 'explorar', subCategory: 'ARTE', baseViews: 9400, compatibility: 'dual' },
  { id: 'exp-win93', name: 'Windows 93', url: 'https://windows93.net', description: 'Uma versão surreal e artística de um sistema operacional antigo.', category: 'explorar', subCategory: 'ARTE DIGITAL', baseViews: 11000, compatibility: 'pc' },
  { id: 'exp-8bit', name: '8BitDash', url: 'https://8bitdash.com', description: 'Wallpapers e rádio lo-fi com estética 8-bit.', category: 'explorar', subCategory: 'ESTILO', baseViews: 4900, compatibility: 'dual' },
  { id: 'exp-tj', name: 'Tjukanovt Maps', url: 'https://tjukanovt.github.io', description: 'Mapas experimentais e visualizações de dados geográficos.', category: 'explorar', subCategory: 'MAPS', baseViews: 2100, compatibility: 'pc' },
  { id: 'exp-insecam', name: 'Insecam', url: 'https://insecam.com', description: 'O maior diretório de câmeras de segurança online públicas do mundo.', category: 'explorar', subCategory: 'CURIOSIDADE', baseViews: 18000, compatibility: 'dual' },
  { id: 'exp-oskar', name: 'Oskar Stålberg', url: 'https://oskarstalberg.com', description: 'Experimentos de arquitetura procedimental e design.', category: 'explorar', subCategory: 'ARTE/DESIGN', baseViews: 6300, compatibility: 'dual' },
  { id: 'exp-engine', name: 'Google Earth Engine', url: 'https://earthengine.google.com', description: 'Análise de dados geoespaciais e mudanças no planeta em tempo real.', category: 'explorar', subCategory: 'MAPS/LABS', baseViews: 12000, compatibility: 'pc' },
  { id: 'exp-taverns', name: 'Here Be Taverns', url: 'https://www.herebetaverns.com', description: 'Gerador instantâneo de PdMs, Itens e Locais para RPG.', category: 'explorar', subCategory: 'RPG TOOLS', baseViews: 3400, compatibility: 'dual' },
  { id: 'exp-frame', name: 'Frame Synthesis', url: 'https://framesynthesis.com', description: 'Simuladores e visualizadores web de alta performance.', category: 'explorar', subCategory: 'LABS', baseViews: 1900, compatibility: 'dual' },
  { id: 'exp-ascii', name: 'Asciimation', url: 'https://asciimation.co.nz', description: 'Star Wars: A New Hope recontado inteiramente em ASCII Art.', category: 'explorar', subCategory: 'RETRO', baseViews: 5200, compatibility: 'pc' },
  { id: 'exp-shark', name: 'OCEARCH', description: 'Rastreador global de tubarões, baleias e tartarugas marinhas ao vivo.', url: 'https://ocearch.org', category: 'explorar', subCategory: 'NATUREZA', baseViews: 7100, compatibility: 'dual' },
  { id: 'exp-noclip', name: 'Noclip Website', url: 'https://noclip.website', description: 'Explore os mapas dos seus jogos favoritos direto no navegador.', category: 'explorar', subCategory: 'GAMES LABS', baseViews: 13000, compatibility: 'pc' },
  { id: 'exp-render', name: 'Renderforest', url: 'https://renderforest.com', description: 'Criação de vídeos, logos e sites em uma plataforma única.', category: 'explorar', subCategory: 'DESIGN', baseViews: 4500, compatibility: 'dual' },
  { id: 'exp-useless', name: 'The Useless Web', url: 'https://theuselessweb.com', description: 'Leva você para sites aleatórios e inúteis na internet.', category: 'explorar', subCategory: 'CURIO', baseViews: 25000, compatibility: 'dual' },
  { id: 'exp-future', name: 'FutureMe', url: 'https://www.futureme.org', description: 'Escreva uma carta para você mesmo no futuro.', category: 'explorar', subCategory: 'EXPERIÊNCIA', baseViews: 9800, compatibility: 'dual' },

  // --- CATEGORIA 7: LEITURA ---
  { id: 'lei-webtoon', name: 'WEBTOON', url: 'https://m.webtoons.com/pt-br/?webtoon-platform-redirect=true', description: 'Maior comunidade de quadrinhos digitais e manhwas do mundo.', category: 'leitura', subCategory: 'QUADRINHOS', baseViews: 15400, compatibility: 'dual' },
  { id: 'lei-5etools', name: '5e Tools', url: 'https://www.5e.tools', description: 'Compêndio completo de regras, monstros e itens para RPG D&D 5ª Edição.', category: 'leitura', subCategory: 'RPG', baseViews: 8900, compatibility: 'dual' },
  { id: 'lei-mangadex', name: 'MangaDex', url: 'https://mangadex.org', description: 'Leitor de mangás online de alta qualidade, sem anúncios e mantido pela comunidade.', category: 'leitura', subCategory: 'MANGÁ', baseViews: 21000, compatibility: 'dual' },
  { id: 'lei-dlivros', name: 'Dlivros', url: 'https://dlivros.com', description: 'Biblioteca digital para download gratuito de livros, apostilas e documentos em PDF.', category: 'leitura', subCategory: 'LIVROS', baseViews: 6700, compatibility: 'dual' },
  { id: 'lei-core', name: 'CORE', url: 'https://core.ac.uk', description: 'Buscador global de artigos científicos e pesquisas de acesso aberto.', category: 'leitura', subCategory: 'ACADÊMICO', baseViews: 4200, compatibility: 'dual' },
  { id: 'lei-welib', name: 'Welib', url: 'https://welib.org', description: 'Plataforma de gestão de bibliotecas digitais voltada para o compartilhamento de conhecimento.', category: 'leitura', subCategory: 'BIBLIOTECA', baseViews: 3100, compatibility: 'dual' },
];
